import { defineStore } from "pinia";
export const useTodoStore = defineStore('todo',{

      state: () => ({
        groups: ["All" , "Milks & Diaries", "Coffees & Teas", "Pet Foods", "Meats", "Vegetables", "Fruits"],
        subscribes: [
          {
            id: 1,
            image_background: new URL ('../assets/img/background.png', import.meta.url),
            image_frontground: new URL ('../assets/img/fresh-apples.png', import.meta.url),
            title_letter: "Don't miss amazing grocery deals",
            title_letter_color: "#253D4E",
            desc_letter: "Sign up for the daily newsletter ",
            desc_letter_color: "rgba(126, 126, 126, 1)",
          },
  
        ],
        searchboxes: [
          {
              id: 1,
              title_color: "black",
              title_size: "16px",
              title_text: "All Categories",
              left_icon: "uil uil-angle-down",
              left_icon_color: "gray",
              left_icon_size: "16px",
              placeholder: "Search for items",
              right_icon: "uil uil-search",
              right_icon_color: "gray",
              right_icon_size: "20px",
          },
      ],
  
  
      subheaders: [
          {
              id: 1,
              browse_left_icon: "uil uil-dice-four",
              browse_left_icon_color: "white",
              browse_left_icon_size: "26px",
              browse_text_color: "white",
              browse_text: "Broswe All Categories",
              browse_right_icon: "uil uil-angle-down",
              browse_right_icon_color: "white",
              browse_right_icon_size: "20px",
              right_icon: "uil uil-headphones-alt",
              right_icon_color: "black",
              right_icon_size: "40px",
              tel: "023 880 880",
              tel_color: "#3BB77E",
              tel_size: "24px",
          }
      ],
  
      menuitems: [
          {
              id: 1,
              first_icon: "uil uil-user",
              text: "Account",
              second_icon: "",
              first_icon_color: "black",
              text_color: "rgba(126, 126, 126, 1)",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 2,
              first_icon: "uil uil-redo",
              text: "Compare",
              second_icon: "",
              first_icon_color: "black",
              text_color: "rgba(126, 126, 126, 1)",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          }, {
              id: 3,
              first_icon: "uil uil-heart",
              text: "Wishlist",
              second_icon: "",
              first_icon_color: "black",
              text_color: "rgba(126, 126, 126, 1)",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 4,
              first_icon: "uil uil-shopping-cart",
              text: "Cart",
              second_icon: "",
              first_icon_color: "black",
              text_color: "rgba(126, 126, 126, 1)",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 5,
              first_icon: "uil uil-fire",
              text: "Hot Deals",
              second_icon: "",
              first_icon_color: "#3BB77E",
              text_color: "black",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 6,
              first_icon: "",
              text: "Home",
              second_icon: "",
              first_icon_color: "#3BB77E",
              text_color: "black",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 7,
              first_icon: "",
              text: "Food",
              second_icon: "uil uil-angle-down",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "black",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 8,
              first_icon: "",
              text: "Vegetables",
              second_icon: "uil uil-angle-down",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "black",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 9,
              first_icon: "",
              text: "Drinks",
              second_icon: "",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 10,
              first_icon: "",
              text: "Cookies",
              second_icon: "",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "",
              first_icon_size: "24px",
              first_text_size: "16px",
              second_icon_size: "",
          },  {
              id: 11,
              first_icon: "",
              text: "Meat & Seafood",
              second_icon: "uil uil-angle-down",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "black",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },  {
              id: 12,
              first_icon: "",
              text: "Bakery",
              second_icon: "",
              first_icon_color: "",
              text_color: "black",
              second_icon_color: "",
              first_icon_size: "24px",
              text_size: "16px",
              second_icon_size: "",
          },
      
      ],
  
      
      
      menus: [
        {
            id: 1,
            title: "Featured Categories",
            menu_color: "black",
        },  {
            id: 2,
            title: "Popular Products",
            title_color: "black",
        },
    
    ],
        promotion: [
            {
              text: "Everyday Fresh & Clean with Our Products",
              img: "./src/assets/img/Onion.png",
              txtBtn: "Shop now",
              btnColor: "#3BB77E",
              bg: "#C3A555"
            }, {
              text: "Make your Breakfast Healthy and Easy",
              img: "./src/assets/img/Juice.png",
              txtBtn: "Shop now",
              btnColor: "#3BB77E",
              bg: "#E0AEA8"
            }, {
              text: "The best Organic Products Online",
              img: "./src/assets/img/Mix_organic.png",
              txtBtn: "Shop now",
              btnColor: "#FDC040",
              bg: "#AADC9D"
            },
          ],
          category: [
            {
              bg: "#f2c8a5",
              img: "./src/assets/img/a.Hamburger.png" ,
              title: "Cake & Milk",
              item: "14 items"
            },
            {
              bg: "#d1cd95",
              img: "../src/assets/img/b.Peace.png",
              title: "Peach",
              item: "17 items"
            },
            {
              bg: "#a3d195",
              img: "../src/assets/img/c.Kiwi.png",
              title: "Oganic Kiwi",
              item: "21 items"
            },
            {
              bg: "#d195a6",
              img: "../src/assets/img/d.apple.png",
              title: "Red Apple",
              item: "68 items"
            },
            {
              bg: "#eafa96",
              img: "../src/assets/img/e.snack.png",
              title: "Snack",
              item: "34 items"
            },
            {
              bg: "#a895d1",
              img: "../src/assets/img/f.Plam.png",
              title: "Black plum ",
              item: "25 items"
            },
            {
              bg: "#b0d195",
              img: "../src/assets/img/g.Vegetable.png",
              title: "Vegetables",
              item: "65 items"
            },
            {
              bg: "#95d1c5",
              img: "../src/assets/img/h.Headphone.png",
              title: "Headphone",
              item: "33 items"
            },
            {
              bg: "#c9d195",
              img: "../src/assets/img/i.Cake.png",
              title: "Cake & Milk",
              item: "63 items"
            },
            {
              bg: "#ffd175",
              img: "../src/assets/img/j.Orange.png",
              title: "Orange",
              item: "63 items"
            }
          ],
        products: [
          {
            id: 1,
            tag: "-17%",
            tagBg: "#3BB77E",
            image: "./src/assets/img/1-Seeds.png",
            category: 3,
            name: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 2,
            tag: "Hot",
            tagBg: "#FD6E6E",
            image: "./src/assets/img/2-Corn.png",
            category: 3,
            name: "All Natural Italian-Style Chicken Meatballs",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 3,
            tag: "Sale",
            tagBg: "#FDC040",
            image: "./src/assets/img/3-Orange.png",
            category: 3,
            name: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 4,
            tag: "",
            tagBg: "",
            image: "./src/assets/img/4-Tomate.png",
            category: 3,
            name: "Foster Farms Takeout Crispy Classic Buffalo Wings",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 5,
            tag: "",
            tagBg: "",
            image: "./src/assets/img/5-BlueDiamond.png",
            category: 3,
            name: "Blue Diamond Almonds Lightly Salted Vegetables",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 6,
            tag: "",
            tagBg: "",
            image: "./src/assets/img/6-Chobani.png",
            category: 3,
            name: "Chobani Complete Vanilla Greek Yogurt",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 7,
            tag: "Sale",
            tagBg: "#FDC040",
            image: "./src/assets/img/7-Canado.png",
            category: 3,
            name: "Canada Dry Ginger Ale – 2 L Bottle - 200ml - 400g",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 8,
            tag: "",
            tagBg: "",
            image: "./src/assets/img/8-Encore.png",
            category: 3,
            name: "Encore Seafoods Stuffed Alaskan Salmon",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 9,
            tag: "",
            tagBg: "",
            image: "./src/assets/img/9-Gorton.png",
            category: 3,
            name: "Gorton's Beer Battered Fish Fillets with soft paper",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
          {
            id: 1,
            tag: "Hot",
            tagBg: "#FD6E6E",
            image: "./src/assets/img/10-Haagen.png",
            category: 3,
            name: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
            rate: "4.0",
            description: "500 gram",
            sellPrice: "2.00",
            discountPercentage: 17,
            discountPrice: "3.00",
          },
        ],
      }),   
})